name: Build Ruby Gem

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.7.4', '3.0', '3.1', '3.2' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
        # change this to (see https://github.com/ruby/setup-ruby#versioning):
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Install github-pages gem 2.7.4
        continue-on-error: true
        run: bundle install
        working-directory: ./.github/workflows
        if: matrix.ruby == '2.7.4'
      - name: Install github-pages gem
        run: |
          gem install github-pages
          gem update --system
        if: matrix.ruby != '2.7.4'
      - name: Install
        run: bundle install
      - name: Build jekyll site
        run: bundle exec jekyll build
      - name: Build the gem
        continue-on-error: true
        run: |
          gem build *.gemspec
          echo `find . -name "*.gem" | tail -1 | awk -F"[/]" '{print $2}'`
      - name: Install theme gems
        continue-on-error: true
        run: |
          gem install type-on-strap
          gem install jekyll-theme-type-on-strap
      - name: GPR
        continue-on-error: true
        run: |
          gem install type-on-strap --version "2.4.9" --source "https://rubygems.pkg.github.com/sylhare"
      - name: Build with Docker
        continue-on-error: true
        run: |
         cd assets && docker build .
