name: Jekyll Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Do not change as jekyll/builder is used by GitHub pages (for compatibility)
        docker-image: [ 'jekyll/builder', 'sylhare/jekyll' ]

    steps:
      - uses: actions/checkout@v4
      - name: Build the site in the container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          ${{ matrix.docker-image }}:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Install packages
        continue-on-error: true
        run: |
          docker pull sylhare/type-on-strap
          docker pull sylhare/jekyll

